#####################################################################################
# Github Action to check references to closed issues in code.
#
# Workflow starts when:
# 1) push on master branch
#
#####################################################################################
name: "Check no closed issue references"

on:
  push:
    branches: [ master ]

jobs:
  check_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Download test-4445-a
        uses: actions/checkout@v2
        with:
          repository: test-4445-a/test-4445-a
          ref: master
          path: test-4445-a

      - name: Check Issues
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        run: |
          cd test-4445-a
          /bin/bash ./.ci/no_old_refs.sh
